### ISSUE TITLE
RuntimeError: Your python version made changes to the bytecode

### ISSUE THREAD

**Issue by alexreg** [1fge/matricula-online-scraper#7]
Running the program gives the following error.

```
b'\x97\x00|\x00j\x00}\x01t\x03t\x05|\x00\xa6\x01\xab\x01\xa6\x01\xab\x01}\x02i\x00}\x03g\x00}\x04|\x02D\x00]A}\x05|\x05|\x03t\x07|\x04\xa6\x01\xab\x01<\x00|\x04\xa0\x04t\x0b|\x05j\x06|\x05j\x07\xa6\x02\xab\x02\xa6\x01\xab\x01\x01\x00\x8cBt\x10j\tr\x16d\x01\xa0\n|\x04\xa6\x01\xab\x01}\x06n\x0ft\x17|\x04\xa6\x01\xab\x01}\x06|\x06|\x01k\x03\x90\x01r\x06t\x19|\x06\xa6\x01\xab\x01\x01\x00t\x19|\x01\xa6\x01\xab\x01\x01\x00t\x1bt\x1dt\x07|\x06\xa6\x01\xab\x01t\x07|\x01\xa6\x01\xab\x01\xa6\x02\xab\x02\xa6\x01\xab\x01D\x00]\xb2}\x07|\x01|\x07\x19\x00|\x06|\x07\x19\x00k\x03r\x8e\t\x00|\x07|\x03v\x00r\x88t\x19|\x03|\x07\x19\x00\xa6\x01\xab\x01\x01\x00t\x19|\x03|\x07d\x03z\n\x19\x00\xa6\x01\xab\x01\x01\x00t\x19t\x03t\x1ft |\x01\xa6\x02\xab\x02\xa6\x01\xab\x01|\x07d\x04z\n|\x07d\x05z\x00\x85\x02\x19\x00\xa6\x01\xab\x01\x01\x00t\x19|\x04|\x07d\x04z\n|\x07d\x05z\x00\x85\x02\x19\x00\xa6\x01\xab\x01\x01\x00n\x01\x8c\x8dt#d\x06\xa6\x01\xab\x01\x82\x01d\x00S\x00d\x00S\x00'
b'\x97\x00|\x00j\x00\x00\x00\x00\x00\x00\x00\x00\x00}\x01t\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x02i\x00}\x03g\x00}\x04|\x02D\x00]A}\x05|\x05|\x03t\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00|\x04\xa0\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x05j\x06\x00\x00\x00\x00\x00\x00\x00\x00|\x05j\x07\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x8cBt\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\t\x00\x00\x00\x00\x00\x00\x00\x00r\x16d\x01\xa0\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x06n\x0ft\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00}\x06|\x06|\x01k\x03\x00\x00\x00\x00\x90\x01r\x06t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x06\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x1b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x1d\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x06\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00t\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00D\x00]\xb2}\x07|\x01|\x07\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x06|\x07\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00k\x03\x00\x00\x00\x00r\x8e\t\x00|\x07|\x03v\x00r\x88t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x03|\x07\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x03|\x07d\x03z\n\x00\x00\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x01\xa6\x02\x00\x00\xab\x02\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00|\x07d\x04z\n\x00\x00|\x07d\x05z\x00\x00\x00\x85\x02\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00t\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x04|\x07d\x04z\n\x00\x00|\x07d\x05z\x00\x00\x00\x85\x02\x19\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00n\x01\x8c\x8dt#\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x06\xa6\x01\x00\x00\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x82\x01d\x00S\x00d\x00S\x00'
Traceback (most recent call last):
  File "/Users/alex/Software/matricula-online-scraper/main.py", line 6, in <module>
    from download_files import Downloader
  File "/Users/alex/Software/matricula-online-scraper/download_files.py", line 11, in <module>
    from encryption_routine import encryption_routine
  File "/Users/alex/Software/matricula-online-scraper/encryption_routine.py", line 5, in <module>
    from js2py.pyjs import *
  File "/opt/homebrew/lib/python3.11/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/opt/homebrew/lib/python3.11/site-packages/js2py/base.py", line 6, in <module>
    from .utils.injector import fix_js_args
  File "/opt/homebrew/lib/python3.11/site-packages/js2py/utils/injector.py", line 224, in <module>
    check(six.get_function_code(check))
  File "/opt/homebrew/lib/python3.11/site-packages/js2py/utils/injector.py", line 220, in check
    raise RuntimeError(
RuntimeError: Your python version made changes to the bytecode
```

**Comment by joholl** [comment]
This is due to an outdated js2py version. This exception is raised starting with python 3.11 (python 3.10 succeeds).

This should fix it for you:
```sh
pip install Js2Py==0.74
```

**Comment by mark70112** [comment]
I believe I had the same error.  Then I installed the js2py and reran the scrape.  Now getting a different error.  See sequence below.  I then went back and ran the example execution from the instructions (python main.py -o ./images -u https://data.matricula-online.eu/en/deutschland/akmb/militaerkirchenbuecher/0001) and got the same error.

C:\Users\marbr\OneDrive\Documents\matricula-online-scraper> python main.py -o ./images -u https://data.matricula-online.eu/en/deutschland/rottenburg-stuttgart/markelsheim/M+0442%252C+B+007
Traceback (most recent call last):
  File "C:\Users\marbr\OneDrive\Documents\matricula-online-scraper\main.py", line 6, in <module>
    from download_files import Downloader
  File "C:\Users\marbr\OneDrive\Documents\matricula-online-scraper\download_files.py", line 11, in <module>
    from encryption_routine import encryption_routine
  File "C:\Users\marbr\OneDrive\Documents\matricula-online-scraper\encryption_routine.py", line 5, in <module>
    from js2py.pyjs import *
  File "C:\Users\marbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\marbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\marbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\marbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marbr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by FranzMo** [comment]
Meine Fehlermeldungen sehen so aus:

**_python "C:\Users\moserfr\matricula-online-scraper\main.py" -o ./images -u https://data.matricula-online.eu/de/????????????????????????????????????
Traceback (most recent call last):
  File "C:\Users\moserfr\matricula-online-scraper\main.py", line 6, in <module>
    from download_files import Downloader
  File "C:\Users\moserfr\matricula-online-scraper\download_files.py", line 11, in <module>
    from encryption_routine import encryption_routine
  File "C:\Users\moserfr\matricula-online-scraper\encryption_routine.py", line 5, in <module>
    from js2py.pyjs import *
  File "C:\Users\moserfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\moserfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\moserfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moserfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\moserfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moserfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3_**
